sudo: false
language: scala
scala:  2.11.7
jdk: oraclejdk8
# Use JDK 8u45+ explicitly
addons:
  apt:
    packages:
      - oracle-java8-installer
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
script:
  - sbt compile
  - sbt clean coverage test
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
env:
  global:
    secure: gjz7bI9ROGjG7S8wW3dwabGBsdi0wsYhcSM6UTwd9JA2GeJXCJVg3uVPd1GAg5iY8elmWhB+aOh7o8b6FdLaFTaz5qTuUWBShNzYgi16glCIpD0yk9d0GASnSxV3SJmnJyTvsYukjkxvrJ6aOwQGZTTJ1+7gudKHwXjYVcVgWk0=
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - sbt coverageReport
  - sbt coverageAggregate
  - sbt codacyCoverage
before_deploy:
  - .travis/publish.sh
  - sbt package  # build light jars
  - sbt assembly # build the fat jar
  - export RELEASE_VERSION=$(ls target/scala-2.11/pathway*.jar | grep -Eow -e '(\d+\.\d+\.\d+-[0-9a-f]+)' -m 1)
  - echo "Releasing $RELEASE_VERSION"
deploy:
  provider: releases
  api_key:
    secure: L6BZnOGDMk1SasV9sxkEOd4gQkKJiaewCLJ6TVZa4E40kIKnZ1L1knxVssgk2v/a5NAcJggLsdU+QJ4AmM2LpCbnMWARHghwMc4W94RUsMPwYizYGBIp4a3MsGPcQ4CgjWN/v1UIpuxHVjyxfEt+4HS6hkQfW6uMXFj14MtVTH4=
  file:
    - "target/scala-2.11/pathway_2.11-${RELEASE_VERSION}.jar"
    - "target/scala-2.11/pathway_2.11-${RELEASE_VERSION}-javadoc.jar"
    - "target/scala-2.11/pathway_2.11-${RELEASE_VERSION}-sources.jar"
    - "target/scala-2.11/pathway-fat-${RELEASE_VERSION}.jar"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/714d475d97646f75819a
    on_success: change
    on_failure: always
    on_start: false
